export enum Path{
    NONE = '',
    DEFAULT = '/',
    LOGIN = 'login',
    NOT_FOUND = 'pagina-nao-encontrada',
    DASHBOARD = 'dashboard',
    INPUTS_OUTPUTS = 'entradas-e-saidas',
    STOCK = 'estoque',
    USERS = 'usuarios',
    NEW_USER = 'novo-usuario',
    EDIT_USER = ':userId',
    CATEGORIES = 'categorias',
    NEW_CATEGORY = 'nova-categoria',
    EDIT_CATEGORY = ':categoryId',
    PRODUCTS = 'produtos',
    NEW_PRODUCT = 'novo-produto',
}
